top:
  - name: The Carpentries
    url: /
    weight: 10
  - name: Data Carpentry
    url: https://datacarpentry.org/
    weight: 20
  - name: Software Carpentry
    url: https://software-carpentry.org/
    weight: 30
  - name: Library Carpentry
    url: https://librarycarpentry.org/
    weight: 40
main:
- identifier: about-us
  name: About us
  url: "#"
  parent: null
  weight: 10
- identifier: about-the-carpentries
  name: About The Carpentries
  url: "/about-us/"
  parent: about-us
  weight: 10
- identifier: governance
  name: Governance
  url: "/about-us/governance/"
  parent: about-us
  weight: 20
- identifier: values
  name: Values
  url: "/about-us/values/"
  parent: about-us
  weight: 30
- identifier: impact
  name: Impact
  url: "/about-us/impact/"
  parent: about-us
  weight: 40
- identifier: team
  name: Team
  url: "/about-us/team/"
  parent: about-us
  weight: 50
- identifier: careers
  name: Careers
  url: "/about-us/careers/"
  parent: about-us
  weight: 60
- identifier: financials
  name: Financials
  url: "/about-us/financials/"
  parent: about-us
  weight: 70
- identifier: publications
  name: Publications
  url: "/about-us/publications/"
  parent: about-us
  weight: 80
- identifier: contact-us
  name: Contact us
  url: "/about-us/contact-us/"
  parent: about-us
  weight: 90
- identifier: learn
  name: Learn
  url: "#"
  parent: null
  weight: 20
- identifier: lessons
  name: Lessons
  url: "#"
  parent: learn
  weight: 10
- identifier: workshops
  name: Workshops
  url: "/workshops/"
  parent: learn
  weight: 20
- identifier: instructor-training
  name: Instructor Training
  url: "#"
  parent: learn
  weight: 30
- identifier: trainer-training
  name: Trainer Training
  url: "#"
  parent: learn
  weight: 40
- identifier: volunteer
  name: Volunteer
  url: "#"
  parent: null
  weight: 30
- identifier: community
  name: Community
  url: "#"
  parent: volunteer
  weight: 10
- identifier: get-involved
  name: Get Involved
  url: "#"
  parent: volunteer
  weight: 20
- identifier: handbook
  name: Handbook
  url: "#"
  parent: volunteer
  weight: 30
- identifier: newsletter
  name: Newsletter
  url: "#"
  parent: volunteer
  weight: 40
- identifier: amy
  name: AMY
  url: "#"
  parent: volunteer
  weight: 50
- identifier: host
  name: Host
  url: "#"
  parent: null
  weight: 40
- identifier: host-a-workshop
  name: Host a workshop
  url: "/workshops/request-workshop/"
  parent: host
  weight: 10
- identifier: host-a-training
  name: Host a training
  url: "#"
  parent: host
  weight: 20
- identifier: pricing
  name: Pricing
  url: "#"
  parent: host
  weight: 30
- identifier: support
  name: Support
  url: "#"
  parent: null
  weight: 50
- identifier: membership
  name: Membership
  url: "#"
  parent: support
  weight: 10
- identifier: donate
  name: Donate
  url: "#"
  parent: support
  weight: 20
- identifier: sponsorship
  name: Sponsorship
  url: "#"
  parent: support
  weight: 30
- identifier: blog
  name: Blog
  url: "/blog/"
  parent: null
  weight: 60
- identifier: donate-btn
  name: Donate
  url: "#"
  params:
    style: button
  weight: 70