top:
  - name: The Carpentries
    url: /
    weight: 10
  - name: Data Carpentry
    url: https://datacarpentry.org/
    weight: 20
  - name: Software Carpentry
    url: https://software-carpentry.org/
    weight: 30
  - name: Library Carpentry
    url: https://librarycarpentry.org/
    weight: 40
about:
- name: About us
  pageRef: /about-us
  weight: 10
- name: Our impact
  pageRef: /about-us/impact
  weight: 20
- name: Our funding
  pageRef: /about-us/funding
  weight: 30
- name: Our team
  pageRef: /about-us/team
  weight: 40
- name: Our community
  pageRef: /about-us/community
  weight: 50
- name: Contact us
  pageRef: /about-us/contact
  weight: 60
workshops:
- name: Workshops
  pageRef: /workshops
  weight: 10
- name: Request a workshop
  pageRef: /workshops/request-workshop
  weight: 20
- name: Workshops FAQ
  pageRef: /workshops/workshops-faq
  weight: 30
- name: Browse lessons
  url: /#
  weight: 40
- name: Upcoming workshops
  pageRef: /workshops/upcoming-workshops
  weight: 50
main:
- identifier: about-us
  name: About us
  url: "#"
  parent: null
  weight: 10
- identifier: about-the-carpentries
  name: About The Carpentries
  pageRef: "/about-us/"
  parent: about-us
  weight: 10
- identifier: governance
  name: Governance
  pageRef: "governance"
  parent: about-us
  weight: 20
- identifier: values
  name: Values
  pageRef: "/about-us/values/"
  parent: about-us
  weight: 30
- identifier: impact
  name: Impact
  pageRef: "/about-us/impact/"
  parent: about-us
  weight: 40
- identifier: team
  name: Team
  pageRef: "/about-us/team/"
  parent: about-us
  weight: 50
- identifier: careers
  name: Careers
  pageRef: "/about-us/careers/"
  parent: about-us
  weight: 60
- identifier: financials
  name: Financials
  pageRef: "/about-us/financials/"
  parent: about-us
  weight: 70
- identifier: publications
  name: Publications
  pageRef: "/about-us/publications/"
  parent: about-us
  weight: 80
- identifier: contact-us
  name: Contact us
  pageRef: "/about-us/contact-us/"
  parent: about-us
  weight: 90
- identifier: learn
  name: Learn
  url: "#"
  parent: null
  weight: 20
- identifier: lessons
  name: Lessons
  pageRef: "#"
  parent: learn
  weight: 10
- identifier: workshops
  name: Workshops
  pageRef: "/workshops/"
  parent: learn
  weight: 20
- identifier: instructor-training
  name: Instructor Training
  pageRef: "/instructor-training/"
  parent: learn
  weight: 30
- identifier: trainer-training
  name: Trainer Training
  pageRef: "/trainer-training/"
  parent: learn
  weight: 40
- identifier: lesson-development
  name: Lesson Development
  pageRef: "/lesson-development/"
  parent: learn
  weight: 50
- identifier: volunteer
  name: Volunteer
  url: "#"
  parent: null
  weight: 30
- identifier: community
  name: Community
  url: "#"
  parent: volunteer
  weight: 10
- identifier: get-involved
  name: Get Involved
  url: "#"
  parent: volunteer
  weight: 20
- identifier: handbook
  name: Handbook
  url: "#"
  parent: volunteer
  weight: 30
- identifier: newsletter
  name: Newsletter
  url: "#"
  parent: volunteer
  weight: 40
- identifier: amy
  name: AMY
  url: "#"
  parent: volunteer
  weight: 50
- identifier: host
  name: Host
  url: "#"
  parent: null
  weight: 40
- identifier: host-a-workshop
  name: Host a workshop
  pageRef: "/workshops/request-workshop/"
  parent: host
  weight: 10
- identifier: host-a-training
  name: Host a training
  url: "#"
  parent: host
  weight: 20
- identifier: pricing
  name: Pricing
  url: "#"
  parent: host
  weight: 30
- identifier: support
  name: Support
  url: "#"
  parent: null
  weight: 50
- identifier: membership
  name: Membership
  url: "#"
  parent: support
  weight: 10
- identifier: donate
  name: Donate
  url: "#"
  parent: support
  weight: 20
- identifier: sponsorship
  name: Sponsorship
  url: "#"
  parent: support
  weight: 30
- identifier: blog
  name: Blog
  pageRef: "/blog/"
  parent: null
  weight: 60
- identifier: donate-btn
  name: Donate
  url: "#"
  params:
    style: button
  weight: 70